export const ProductsActionTypes = {
  FETCH_DRINKS_START: "FETCH_DRINKS_START",
  FETCH_DRINKS_SUCCESS: "FETCH_DRINKS_SUCCESS",
  FETCH_DRINKS_FAILURE: "FETCH_DRINKS_FAILURE",
  FETCH_SINGLE_DRINK_START: "FETCH_SINGLE_DRINK_START",
  FETCH_SINGLE_DRINK_SUCCESS: "FETCH_SINGLE_DRINK_SUCCESS",
  SINGLE_DRINK_UNMOUNT: "SINGLE_DRINK_UNMOUNT",
  FETCH_FLAVOURS_START: "FETCH_FLAVOURS_START",
  FETCH_FLAVOURS_SUCCESS: "FETCH_FLAVOURS_SUCCESS",
  FETCH_FLAVOURS_FAILURE: "FETCH_FLAVOURS_FAILURE",
  FETCH_SINGLE_FLAVOUR_START: "FETCH_SINGLE_FLAVOUR_START",
  FETCH_SINGLE_FLAVOUR_SUCCESS: "FETCH_SINGLE_FLAVOUR_SUCCESS",
  SINGLE_FLAVOUR_UNMOUNT: "SINGLE_FLAVOUR_UNMOUNT",
};
